"""add start_date and end_date to exams

Revision ID: 08619c7307e7
Revises: a52cd85384a4
Create Date: 2026-04-28 22:19:18.301103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08619c7307e7'
down_revision = 'a52cd85384a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
