"""Add student_id to AttemptModel

Revision ID: 0f6407f4c760
Revises: 4c507aa265bb
Create Date: 2026-06-04 12:17:03.807797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f6407f4c760'
down_revision = '4c507aa265bb'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('student_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_student_attempts_student_id'), ['student_id'], unique=False)

    # Backfill existing rows with UUIDs
    op.execute("UPDATE student_attempts SET student_id = gen_random_uuid() WHERE student_id IS NULL;")

    # Set default for future inserts
    op.execute("ALTER TABLE student_attempts ALTER COLUMN student_id SET DEFAULT gen_random_uuid();")


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_attempts_student_id'))
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
