"""Initial migration

Revision ID: 100094357824
Revises: ea7372d3cf4c
Create Date: 2026-04-26 11:02:57.188395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100094357824'
down_revision = 'ea7372d3cf4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('violation_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('violation_log', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('auto_submitted_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_violation_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_attempts', schema=None) as batch_op:
        batch_op.drop_column('last_violation_time')
        batch_op.drop_column('auto_submitted_reason')
        batch_op.drop_column('violation_log')
        batch_op.drop_column('violation_count')

    # ### end Alembic commands ###
