"""Initial migration

Revision ID: 1c8b8b7e8704
Revises: af0db0f463ca
Create Date: 2026-03-26 00:10:52.324317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c8b8b7e8704'
down_revision = 'af0db0f463ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_order', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_attempts', schema=None) as batch_op:
        batch_op.drop_column('question_order')

    # ### end Alembic commands ###
