"""add size to demo_requests

Revision ID: 484cabdecb07
Revises: 67edb8cb6d80
Create Date: 2026-04-28 14:08:43.683280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484cabdecb07'
down_revision = '67edb8cb6d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demo_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demo_requests', schema=None) as batch_op:
        batch_op.drop_column('size')

    # ### end Alembic commands ###
