"""convert is_correct integer to boolean

Revision ID: 4c507aa265bb
Revises: a8bbd28b31f3
Create Date: 2026-05-20 11:29:03.309597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c507aa265bb'
down_revision = 'a8bbd28b31f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_answers', schema=None) as batch_op:
        batch_op.alter_column('is_correct',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_answers', schema=None) as batch_op:
        batch_op.alter_column('is_correct',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
