"""add phone to demo_requests

Revision ID: 67edb8cb6d80
Revises: 100094357824
Create Date: 2026-04-28 13:57:15.480558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67edb8cb6d80'
down_revision = '100094357824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demo_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demo_requests', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
