"""add phone to contact messages

Revision ID: 741bd32ac87e
Revises: 926fc660d202
Create Date: 2026-05-11 22:10:54.726495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741bd32ac87e'
down_revision = '926fc660d202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
