"""Initial migration

Revision ID: a07d816df605
Revises: 1c8b8b7e8704
Create Date: 2026-03-26 00:54:37.453466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07d816df605'
down_revision = '1c8b8b7e8704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option_order', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_attempts', schema=None) as batch_op:
        batch_op.drop_column('option_order')

    # ### end Alembic commands ###
