"""Initial migration

Revision ID: b18815592bdd
Revises: a07d816df605
Create Date: 2026-03-26 11:10:01.314516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18815592bdd'
down_revision = 'a07d816df605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_submitted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_attempts', schema=None) as batch_op:
        batch_op.drop_column('is_submitted')

    # ### end Alembic commands ###
