"""Initial migration

Revision ID: ea7372d3cf4c
Revises: b606ff10864c
Create Date: 2026-04-12 22:08:32.825061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea7372d3cf4c'
down_revision = 'b606ff10864c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               nullable=True)
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('phone')

    with op.batch_alter_table('demo_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               nullable=True)
        batch_op.alter_column('school_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.drop_column('phone')
        batch_op.drop_column('size')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demo_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), nullable=False))
        batch_op.alter_column('school_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('status')
        batch_op.drop_column('message')

    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), nullable=False))
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('status')

    # ### end Alembic commands ###
